### ISSUE TITLE
nested traverse sql cause syntax error

### ISSUE THREAD

**Issue by crossknight** [nogdb/nogdb#11]
Cannot use traverse clause inside select

Current output
nogdb::SQL::execute: syntax error near traverse
40962 SQL_SYNTAX_ERROR: A SQL syntax error. (select dataID from (traverse out() from #23:195) where @className != 'DataHolder' and @className != 'DataContent' and @className != 'User' and dataID != 'CFCCategory#0162F61271924F37C2D431764ECD81A8388157B50346')

Expected output
No error(s)

**Comment by pj4dev** [comment]
This issue has been fixed in PR #16
