### ISSUE TITLE
SQL_INVALID_PROJECTION after get out-of-bound index in sql

### ISSUE THREAD

**Issue by crossknight** [nogdb/nogdb#12]
Current output

Error was thrown if out('allUsers') is empty

40969 SQL_INVALID_PROJECTION: Projection(s) of select statement is invalid. (select from (select dataID, out('allUsers')[0].dataID as userID from Data where dataID in ['CFCCategory#0162F612CC89576A7D50549946A6871830B94CCF5077']) where userID is not NULL)

Expect output
No error(s). 
out('allUsers')[0].dataID as userID => userID is empty string

**Comment by pj4dev** [comment]
This issue has already been fixed in PR #14
