### ISSUE TITLE
a single quote in sql statement may causes sql syntax error

### ISSUE THREAD

**Issue by crossknight** [nogdb/nogdb#18]
create a edge with an attribute value \"TEST\"'te\ta\bst'\\'EIEI\\'message.\rwithNewLine.\n\nEIEI\\\\ causes sql syntax error

result :
nogdb::SQL::execute: syntax error near 'te'
40962 SQL_SYNTAX_ERROR: A SQL syntax error. (create edge allUsers from (select from CFCCategory where dataID='CFCCategory#0163966BEDE7C20AB73D892749E289801B8C647225EF') to (select from User where dataID='User#0163966BEDE0DF7476565FB64F7A8A36C433AF3CDFDA') set testEdgeAttr='\"TEST\"\'te    ast\'\\\'EIEI\\\'message.\rwithNewLine.\n\nEIEI\\\\', myNumber=100)

**Comment by pj4dev** [comment]
This issue has been fixed in PR #25
