### ISSUE TITLE
Syntax error on <cond> OR <multi-cond> SQL clause

### ISSUE THREAD

**Issue by crossknight** [nogdb/nogdb#20]
Syntax error occurred on <cond> OR <multi-cond> SQL clause

Example 
nogdb::SQL::execute: syntax error near 'and'
40962 SQL_SYNTAX_ERROR: A SQL syntax error. (select from (select @className, outV().dataID as outID, inV().dataID as inID from (select expand(rid) from (select @recordId as rid from (select expand(bothE()) from (select expand(in('allUsers')) from User where dataID='User#0163BA99ADFDF8032819D7784A22A578DEF00C0B5C66') where dataID in ['CFCTask#0163BA99AE217636818650B64E05922ECE27FFE417E3','CFCTask#0163BA99AE2CFBCBD522727F48C1BCD62BE1D9FE7072','CFCSubtask#0163BA99AE3ABB9DAA57D2844B249F111964ED389267']) where @className != 'toDataHolder' and @className != 'toDataHolderPv' and @className != 'toDelete' and @className != 'to_transaction'))) where (inID like 'User%') or ((not (inID like 'User%')) and (outID in ['CFCSubtask#0163BA99AE45F1EEBEDDF3554CCB932A580210579DAE','CFCSubtask#0163BA99AE4085C679B469CB4FF19D34AA9B84D3A2E2','CFCTask#0163BA99AE2CFBCBD522727F48C1BCD62BE1D9FE7072','CFCTask#0163BA99AE217636818650B64E05922ECE27FFE417E3','CFCSubtask#0163BA99AE3ABB9DAA57D2844B249F111964ED389267','CFCCategory#0163BA99AE0E51BEE332ABB64E4AA5C832BFFBB485AC']) and (inID in ['CFCSubtask#0163BA99AE45F1EEBEDDF3554CCB932A580210579DAE','CFCSubtask#0163BA99AE4085C679B469CB4FF19D34AA9B84D3A2E2','CFCTask#0163BA99AE2CFBCBD522727F48C1BCD62BE1D9FE7072','CFCTask#0163BA99AE217636818650B64E05922ECE27FFE417E3','CFCSubtask#0163BA99AE3ABB9DAA57D2844B249F111964ED389267','CFCCategory#0163BA99AE0E51BEE332ABB64E4AA5C832BFFBB485AC'])))
 
More specific example 
select from vertex where (a like 'a%') or (not(a like 'a%') and b in ['string'] and a in ['string'])

**Comment by pj4dev** [comment]
This issue has been fixed in PR #25
