### ISSUE TITLE
Select walk[condition].property may cause segmentation fault

### ISSUE THREAD

**Issue by crossknight** [nogdb/nogdb#28]
Select walk[condition].property may cause segmentation fault

Example
SELECT outE('toDataHolderPv')[userID='User#0163D8EB3431B1D5AE1473F9478CBF1509A621BE2382'].inV()[0].versionKeeped from Data where dataID='CFCCategory#0163D8EB33BE3A0D39F496104694A3C2D951FB1FE01B'

**Comment by pj4dev** [comment]
This bug has been fixed in PR #42
