### ISSUE TITLE
[Request] Collection Data Types

### ISSUE THREAD

**Issue by crossknight** [nogdb/nogdb#37]
Request collection data types like Array, Set, Dictionary
Keys or Values of Array, Set, Dictionary have to use as conditions to search records

**Comment by crossknight** [comment]
What about "Keys or Values of Array, Set, Dictionary have to use as conditions to search records" part?

**Comment by phirasit** [comment]
Keys and Values of Collections can be anything that can be parsed with this API (e.g. primitive types, string, Arrays, Vectors inside Vectors etc). The API will recursively parse the data into bytes.

**Comment by crossknight** [comment]
No, I mean How to use Keys or Values of Collections to search specific record.
For example, I have 2 records with these properties
[classA : {"key" : "value1"}], [classA : {"key" : "value2"}]
and I want to get the record of classA that has key = "value1"

**Comment by phirasit** [comment]
You should be doing something like this

```
auto vertexCondition = [](const nogdb::Record &record) {
    using classA_type = std::map<std::string, std::string>;
    return (record.get("classA").convert<classA_type>().at("key") == "value1");
};
```

**Comment by pj4dev** [comment]
Hi,

To simplify this functionality, perhaps we need additional implementations in SQL parser. It would support such a search condition with records having properties as in the example without creating a conditional function manually.

Once key/value pairs have been inserted via SQL, the underlying parser may create a collection - Map<string, string> - to store these properties. For data retrieval, it may be simply using the conditional function (like shown in @phirasit's comment above) to query and parse the result.
