### ISSUE TITLE
NogDB:SQL-Update and delete return void

### ISSUE THREAD

**Issue by 028928768** [nogdb/nogdb#43]
- when execute update and delete command via SQL, it returns no result.
- Front-end-team cannot acknowledge what is really change within inside database whether it is deleted/updated or not.
- Request : executing update or delete sql command return result object consist of ( NodeID,EdgeID, New Properties ).

**Comment by kasidej** [comment]
update and delete sql command will return `SQL::Result::Type::RECORD_DESCRIPTORS` (`vector<RecordDescriptor>`)

**Comment by pj4dev** [comment]
This bug has been fixed in PR #44
